spring:
  data:
    mongodb:
      host: localhost
      port: 9071
      username: weather
      password: weatherpwd
server:
  port : 9073

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG